name: demo_plasma
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest prioriy
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - jupyterlab>=3
  - nbresuse
  - nodejs
  - r-irkernel
  - r-base>=4
  - r-tidyverse
  - r-diagram
  - bioconductor-biostrings

